language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
env:
  - FLASK_ENV=testing
script:
  - pytest --cov src
after_success:
  - bash <(curl -s https://codecov.io/bash)
