"""empty message

Revision ID: 18d1411d6f37
Revises: 5851328b8f7b
Create Date: 2020-08-06 06:01:13.708520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d1411d6f37'
down_revision = '5851328b8f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('published_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'published_on')
    # ### end Alembic commands ###
