"""empty message

Revision ID: 213a0324b416
Revises: 795f55e2e015
Create Date: 2020-09-06 11:59:27.856992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213a0324b416'
down_revision = '795f55e2e015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_feed_assoc', sa.Column('custom_topic_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_feed_assoc', 'custom_topic_id')
    # ### end Alembic commands ###
