"""Add added_on column to user_feed_map

Revision ID: 36a708b3372f
Revises: 5252a68bbc2b
Create Date: 2020-08-22 22:15:03.342231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a708b3372f'
down_revision = '5252a68bbc2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_feed_map', sa.Column('added_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_feed_map', 'added_on')
    # ### end Alembic commands ###
