"""topics, rssfeeds and articles tables

Revision ID: 4f4a5ab204b5
Revises: 
Create Date: 2020-07-05 22:46:20.607873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4a5ab204b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_name')
    )
    op.create_table('rss_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rss_link', sa.Text(), nullable=False),
    sa.Column('site_name', sa.String(length=30), nullable=False),
    sa.Column('site_url', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rss_link'),
    sa.UniqueConstraint('site_url')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('rssfeed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rssfeed_id'], ['rss_feed.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('rss_feed')
    op.drop_table('topic')
    # ### end Alembic commands ###
