"""Change site_name to feed_name, increase topic_name and feed_name sizes

Revision ID: 5252a68bbc2b
Revises: d5b58448b93d
Create Date: 2020-08-14 16:33:20.690548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5252a68bbc2b'
down_revision = 'd5b58448b93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_feed', sa.Column('feed_name', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_rss_feed_feed_name'), 'rss_feed', ['feed_name'], unique=True)
    op.drop_index('ix_rss_feed_site_name', table_name='rss_feed')
    op.drop_column('rss_feed', 'site_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_feed', sa.Column('site_name', sa.VARCHAR(length=30), nullable=False))
    op.create_index('ix_rss_feed_site_name', 'rss_feed', ['site_name'], unique=1)
    op.drop_index(op.f('ix_rss_feed_feed_name'), table_name='rss_feed')
    op.drop_column('rss_feed', 'feed_name')
    # ### end Alembic commands ###
