"""Add published_on column for articles

Revision ID: 5851328b8f7b
Revises: f0d787d64302
Create Date: 2020-08-06 04:24:23.543423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5851328b8f7b'
down_revision = 'f0d787d64302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('published_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'published_on')
    # ### end Alembic commands ###
