"""empty message

Revision ID: 705e3849f60f
Revises: d776fcad8772
Create Date: 2020-07-08 19:55:28.436961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705e3849f60f'
down_revision = 'd776fcad8772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feed_map',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['rss_feed.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'feed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feed_map')
    # ### end Alembic commands ###
