"""Add ondelete, onupdate rules for UserRole

Revision ID: 77bc5d99dcd9
Revises: c9455abd6fa8
Create Date: 2020-08-07 06:32:34.138618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bc5d99dcd9'
down_revision = 'c9455abd6fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Edited: changed to batch operation for SQLite3 support
    with op.batch_alter_table('user') as batch_op:
        batch_op.create_foreign_key('fk_user_role', 'user_role', ['role_id'], ['id'], onupdate='CASCADE', ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
