"""empty message

Revision ID: 795f55e2e015
Revises: 36a708b3372f
Create Date: 2020-08-29 05:58:08.904521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795f55e2e015'
down_revision = '36a708b3372f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feed_assoc',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.Column('custom_feed_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['rss_feed.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'feed_id')
    )
    op.drop_table('user_feed_map')
    op.add_column('rss_feed', sa.Column('feed_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_feed', 'feed_type')
    op.create_table('user_feed_map',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('feed_id', sa.INTEGER(), nullable=False),
    sa.Column('added_on', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['rss_feed.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'feed_id')
    )
    op.drop_table('user_feed_assoc')
    # ### end Alembic commands ###
