"""empty message

Revision ID: 898324c7fe3d
Revises: 241e8fb3e64b
Create Date: 2020-07-07 18:03:34.684942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898324c7fe3d'
down_revision = '241e8fb3e64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
