"""empty message

Revision ID: 9701005f85db
Revises: 1e4a732de3c5
Create Date: 2020-07-19 13:43:48.906615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9701005f85db'
down_revision = '1e4a732de3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('refreshed_on', sa.DateTime(), nullable=True))
    op.add_column('rss_feed', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_feed', 'updated_on')
    op.drop_column('article', 'refreshed_on')
    # ### end Alembic commands ###
