"""empty message

Revision ID: c86a22bf3a9e
Revises: cc7fe9df2f78
Create Date: 2020-09-10 12:45:14.081383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86a22bf3a9e'
down_revision = 'cc7fe9df2f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rss_feed_feed_name', table_name='rss_feed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rss_feed_feed_name', 'rss_feed', ['feed_name'], unique=1)
    # ### end Alembic commands ###
