"""empty message

Revision ID: cc7fe9df2f78
Revises: 213a0324b416
Create Date: 2020-09-08 17:30:36.774695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7fe9df2f78'
down_revision = '213a0324b416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_topic_topic_name'), 'topic', ['topic_name'], unique=True)
    op.drop_index('topic_name', table_name='topic')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user_role', ['role_id'], ['id'], onupdate='CASCADE', ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'user_role', ['role_id'], ['id'])
    op.create_index('topic_name', 'topic', ['topic_name'], unique=True)
    op.drop_index(op.f('ix_topic_topic_name'), table_name='topic')
    # ### end Alembic commands ###
