"""MySQL support

Revision ID: d5b58448b93d
Revises: 77bc5d99dcd9
Create Date: 2020-08-08 19:45:46.900440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b58448b93d'
down_revision = '77bc5d99dcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_topic_topic_name'), 'topic', ['topic_name'], unique=True)
    op.drop_index('topic_name', table_name='topic')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user_role', ['role_id'], ['id'], onupdate='CASCADE', ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'user_role', ['role_id'], ['id'])
    op.create_index('topic_name', 'topic', ['topic_name'], unique=True)
    op.drop_index(op.f('ix_topic_topic_name'), table_name='topic')
    # ### end Alembic commands ###
