"""Add bookmarked_on column to user_article_map

Revision ID: d951c5eaa17e
Revises: 9701005f85db
Create Date: 2020-07-20 11:09:07.091245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd951c5eaa17e'
down_revision = '9701005f85db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_article_map', sa.Column('bookmarked_on', sa.DateTime(), server_default='datetime.utcnow', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_article_map', 'bookmarked_on')
    # ### end Alembic commands ###
