"""empty message

Revision ID: f0d787d64302
Revises: d951c5eaa17e
Create Date: 2020-07-23 18:08:12.401239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d787d64302'
down_revision = 'd951c5eaa17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_frequency', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_frequency')
    # ### end Alembic commands ###
